export const MAJOR_DATA = [
  {id: null, value: '학과를 선택하세요.'},
  {id: '001', value: '건축학전공'},
  {id: '002', value: '게임소프트웨어전공'},
  {id: '003', value: '경영학전공'},
  {id: '004', value: '국제통상학과전공'},
  {id: '005', value: '만화애니메이션학전공'},
  {id: '006', value: '미디어커뮤니케이션학전공'},
  {id: '007', value: '미래자동차융합공학과'},
  {id: '008', value: '사진영상학전공'},
  {id: '009', value: '산업디자인학전공'},
  {id: '010', value: '스마트 IT 전공'},
  {id: '011', value: '유아교육과'},
  {id: '012', value: '유아특수교육과'},
  {id: '013', value: '자동차시스템공학전공'},
  {id: '014', value: '전기전자공학전공'},
  {id: '015', value: '전자출판인쇄공학전공'},
  {id: '016', value: '정보보호학전공'},
  {id: '017', value: '중등특수교육과'},
  {id: '018', value: '초등특수교육과'},
  {id: '019', value: '토목공학전공'},
  {id: '020', value: '토탈패션산업학과'},
]

export default MAJOR_DATA;